# Generated by Django 4.0.4 on 2022-05-21 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BREAD', 'BREAD'), ('SOAP', 'SOAP'), ('BAKING', 'BAKING'), ('SNACKS', 'SNACKS'), ('BEVERAGES', 'BEAVERAGES'), ('PASTA/RICE', 'PASTA/RICE'), ('PERSONAL CARE', 'PERSONAL CARE'), ('SAUCES/OILS', 'SAUCES/OILS'), ('PERSONAL CARE', 'PERSONAL CARE'), ('OTHERS', 'OTHERS')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('amount', models.FloatField()),
                ('quatinty', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='ProductManager.productcategory')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
