# Generated by Django 4.0.4 on 2022-05-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('BREAD', 'BREAD'), ('SOAP', 'SOAP'), ('BAKING', 'BAKING'), ('SNACKS', 'SNACKS'), ('BEVERAGES', 'BEAVERAGES'), ('PASTA/RICE', 'PASTA/RICE'), ('PERSONAL CARE', 'PERSONAL CARE'), ('SAUCES/OILS', 'SAUCES/OILS'), ('PERSONAL CARE', 'PERSONAL CARE'), ('OTHERS', 'OTHERS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
