# Generated by Django 4.0.4 on 2022-05-21 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManager', '0002_alter_products_category_alter_products_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='total',
        ),
    ]
