# Generated by Django 4.0.4 on 2022-05-22 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManager', '0005_category_alter_products_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='quatinty',
            new_name='qauntity',
        ),
    ]
