# Generated by Django 4.0.4 on 2022-05-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManager', '0006_rename_quatinty_products_qauntity'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='total_cost',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
