# Generated by Django 4.0.4 on 2022-05-31 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManager', '0007_products_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='total_cost',
        ),
    ]
